categories:
  tissue:
    search_terms:
      - tissue
    specific_products: []
    vendors:
      - coles
  toilet_paper:
    search_terms:
      - toilet paper
    specific_products: []
    vendors:
      - coles