categories:
  tissue:
    search_terms:
      - tissue
    vendors:
      - coles
    specific_products:
      coles:
        - "9092540"
        - "9161519"
        - "6325314"
  toilet_paper:
    search_terms:
      - toilet paper
    vendors:
      - coles
    specific_products:
      coles:
        - "9152370"
        - "1145428"
        - "1619475"
  granola:
    search_terms:
      - granola
    vendors:
      - coles
    specific_products:
      coles:
        - "2372797"
        - "5297417"
        - "3779450"
        - "8953690"
        - "8957501"
        - "1135311"
        - "9026740"
        - "7062550"
        - "7062560"