categories:
  tissue:
    search_terms:
      - "tissue"
    vendors:
      - "woolworths"
      - "coles"
    specific_products:
      coles:
        - "9092540"
        - "9161519"
        - "6325314"
      woolworths:
        - "759496"
        - "237935"
        - "644239"
    must_include_terms:
      - "tissue"
    must_exclude_terms:
      - "toilet"

  toilet_paper:
    search_terms:
      - "toilet paper"
    vendors:
      - "woolworths"
      - "coles"
    specific_products:
      coles:
        - "9152370"
        - "1145428"
        - "1619475"
      woolworths:
        - "390686"
        - "785129"
        - "6005360"
        - "580263"
      chemist_warehouse:
        - /buy/80010/kleenex-facial-tissues-250-jumbo-white
    must_include_terms:
      - "toilet"
    or_include_terms:
      - "paper"
      - "tissue"

  granola:
    search_terms:
      - "granola"
    vendors:
      - "woolworths"
      - "coles"
    specific_products:
      coles:
        - "5297417"
        - "3779450"
        - "8953690"
        - "8957501"
        - "1135311"
        - "9026740"
        - "7062550"
        - "7062560"
      woolworths:
        - "147307"
        - "6054840"
        - "686551"
        - "6054597"
        - "148981"
        - "6054590"
        - "208900"
    must_exclude_terms:
      - "yoghurt"
      - "bar"
    
  shampoo:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
      - "/buy/86965/alpecin-caffeine-shampoo-c1-375ml"
      - "/buy/77857/alpecin-caffeine-shampoo-c1-250ml"
  barrier_cream:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
    - "/buy/79687/avene-cicalfate-restorative-protective-cream-100ml-multi-purpose-repair-cream"
    - "/buy/122042/la-roche-posay-cicaplast-baume-b5-100ml"
    - "/buy/122041/la-roche-posay-cicaplast-baume-b5-40ml"
  body_wash:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
    - "/buy/64484/palmolive-naturals-body-wash-milk-cherry-blossom-shower-gel-1l"
    - "/buy/63255/palmolive-naturals-body-wash-milk-honey-shower-gel-1l"
    - "/buy/72200/palmolive-naturals-body-wash-milk-orchid-shower-gel-1l"
    - "/buy/64487/palmolive-naturals-body-wash-pomegranate-with-mango-shower-gel-1l"
    - "/buy/63253/palmolive-shower-gel-anti-stress-1-litre"
    - "/buy/65521/enya-body-wash-vanilla-bean-almond-1-litre"
    - "/buy/91155/dettol-shower-cream-peach-raspberry-950ml-profresh-body-wash"
  hand_wash:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
      - "/buy/66511/palmolive-naturals-softening-liquid-hand-wash-aloe-vera-chamomile-refill-save-1l"
      - "/buy/66510/palmolive-naturals-nourishing-liquid-hand-wash-milk-honey-refill-save-1l"
      - "/buy/91511/dettol-hand-wash-aloe-vera-refill-950ml-vitamin-e-antibacterial-liquid"
      - "/buy/115455/bosistos-desert-lime-eucalyptus-hand-wash-refill-1l"
      - "/buy/115454/bosistos-banksia-flower-lavender-hand-wash-refill-1l"
      - "/buy/152925/palmolive-luminous-oils-hand-wash-mandarin-rosemary-refill-1l"
      - "/buy/66509/palmolive-antibacterial-gentle-clean-liquid-hand-wash-refill-save-1l"

  goodnight_pads:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
      chemist_warehouse:
        - "/buy/89413/libra-pad-extra-goodnight-20-pack"
        - "/buy/44797/libra-pads-goodnights-10"
        - "/buy/74835/libra-goodnights-pads-ultra-thin-20"
        - "/buy/157225/libra-pad-ultrathin-goodnight-10-pack"
        - "/buy/88803/u-by-kotex-maxi-pad-overnight-long-wing-8-pack"
        - "/buy/88177/u-by-kotex-ultra-thin-overnight-long-wing-8-pack"
        - "/buy/61260/u-by-kotex-extra-overnight-pads-wing-10-pack"
        - "/buy/58869/u-by-kotex-ultrathin-overnight-regular-with-wings-pads-10"
        - "/buy/37871/stayfree-super-pads-with-wings-12-pack"
        - "/buy/66115/stayfree-all-night-sanitary-pads-with-wings-10-pack"

  regular_pads:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
      chemist_warehouse:
        - "/buy/31497/libra-pads-ultra-thins-with-wings-regular-14"
        - "/buy/44564/kotex-u-ultra-thin-wings-regular-14"
        - "/buy/61258/u-by-kotex-extra-pads-wing-regular-16-pack"
        - "/buy/141193/u-by-kotex-ultrathin-regular-wing-bulk-pack-20"
        - "/buy/35507/libra-pads-wings-regular-14"
        - "/buy/83568/libra-ultra-thins-pads-wings-regular-20"

  liners:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
      chemist_warehouse:
        - "/buy/88320/carefree-breathable-unscented-panty-liners-48-pack"
        - "/buy/119223/libra-liner-extra-protect-50-pack"
        - "/buy/119222/libra-liner-dry-long-30-pack"
        - "/buy/68891/u-by-kotex-designer-series-liners-protect-30-pack"
        - "/buy/122563/libra-liner-flexi-double-liner-thin-2-in-1-25-pack"

  small_pads:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
      chemist_warehouse:
        - "/buy/85219/libra-girl-pads-regular-wing-12-pack"
        - "/buy/165328/u-by-kotex-ultra-thin-teen-regular-wing-pad-14-pack"

  lip_balm:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
      chemist_warehouse:
        - "/buy/86416/dermal-therapy-lip-balm-10g"
        - "/buy/116565/dermal-therapy-lip-balm-manuka-honey-10g"
        - "/buy/130577/dermal-therapy-overnight-lip-repair-10ml"
        - "/buy/103528/dermal-therapy-lip-balm-berry-10g"
        - "/buy/122727/dermal-therapy-lip-balm-sensitive-10g"

  dental_floss:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
      chemist_warehouse:
        - "/buy/84551/oral-b-essential-floss-2x50m"
        - "/buy/44322/colgate-total-tartar-control-durable-oral-care-dental-floss-25m"
        - "/buy/122602/colgate-dental-floss-total-mint-waxed-100m"
        - "/buy/53999/oral-b-floss-waxed-mint-50m"
        - "/buy/84550/oral-b-pro-health-clinical-floss-40m"
        - "/buy/65037/colgate-total-waxed-dental-floss-50m"

  toothpaste:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
      chemist_warehouse:
        - "/buy/112555/colgate-toothpaste-triple-action-cavity-protection-fluoride-original-mint-value-pack-210g"
        - "/buy/116028/colgate-toothpaste-advanced-whitening-tartar-115g"
        - "/buy/137393/colgate-toothpaste-optic-white-purple-100g"
        - "/buy/90691/colgate-toothpaste-total-mint-stripe-antibacterial-fluoride-gel-115g"
        - "/buy/112554/colgate-toothpaste-cavity-protection-great-regular-value-pack-240g"
        - "/buy/107630/oral-b-toothpaste-gum-care-intensive-clean-110g"
        - "/buy/116030/colgate-toothpaste-advanced-whitening-charcoal-180g"
        - "/buy/102274/sensodyne-toothpaste-daily-care-whitening-160g-exclusive-size"
        - "/buy/65794/colgate-toothpaste-sensitive-prorelief-enamel-repair-110g"

  toothbrush:
    search_terms: []
    vendors:
      - "chemist_warehouse"
    specific_products:
      chemist_warehouse:
        - "/buy/66129/colgate-zig-zag-deep-interdental-clean-toothbrush-medium-value-6-pack"
        - "/buy/151216/oral-b-toothbrush-cross-action-7-benefits-5-pack"

  hair_vinegar:
    search_terms: []
    vendors:
      - skin_seoul
    specific_products:
      skin_seoul:
        - "https://skin-seoul.com/product/raspberry-hair-vinegar/"
  
  sunscreen:
    search_terms: []
    vendors:
      - skin_seoul
    specific_products:
      skin_seoul:
        - "https://skin-seoul.com/product/madagascar-centella-hyalu-cica-water-fit-sun-serum-100ml/"
        - "https://skin-seoul.com/product/madagascar-centella-hyalu-cica-waterfit-sun-serum/" # 50mL
        - "https://skin-seoul.com/product/beauty-of-joseon-relief-sun-aqua-fresh-rice-b5/" # 50mL
        - "https://skin-seoul.com/product/beauty-of-joseon-relief-sun-rice-probiotics/" # 50mL
        - "https://skin-seoul.com/product/skin1004-centella-airfit-suncream-light/" # 50mL

  korean_moisturiser:
    search_terms: []
    vendors:
      - skin_seoul
    specific_products:
      skin_seoul:
        - "https://skin-seoul.com/product/345-relief-cream/" # 50mL
        - "https://skin-seoul.com/product/purito-mighty-bamboo-panthenol-cream/" # 100mL